In [138]:
import pandas as pd 
import os 
import numpy as np 


In [139]:
def drop_columns(df,cols):
    for col in cols:
        try:
            df.drop([col],inplace=True,axis=1)
        except Exception as e:
            print(f"Bir hata oluştu{e}")

In [140]:
df = pd.read_csv('emlakVerileri/01.csv')

In [141]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   img-link href        1416 non-null   object
 1   photo-count          1416 non-null   int64 
 2   list-view-price      1416 non-null   object
 3   list-view-date       1416 non-null   object
 4   left                 1416 non-null   object
 5   celly                1416 non-null   object
 6   celly 2              1416 non-null   object
 7   celly 3              1416 non-null   object
 8   celly 4              1247 non-null   object
 9   list-view-location   1416 non-null   object
 10  img-wrp href         642 non-null    object
 11  he-lazy-image src    1321 non-null   object
 12  he-lazy-image src 2  563 non-null    object
 13  list-view-header     1412 non-null   object
dtypes: int64(1), object(13)
memory usage: 155.0+ KB
None


In [142]:
files = os.listdir('emlakVerileri')
df =pd.concat([pd.read_csv(f"emlakVerileri/{file}") for file in files], ignore_index=True)

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   img-link href        8136 non-null   object 
 1   photo-count          8130 non-null   float64
 2   list-view-price      8136 non-null   object 
 3   list-view-date       8136 non-null   object 
 4   left                 8114 non-null   object 
 5   celly                8136 non-null   object 
 6   celly 2              8136 non-null   object 
 7   celly 3              8136 non-null   object 
 8   celly 4              6858 non-null   object 
 9   list-view-location   8136 non-null   object 
 10  img-wrp href         4555 non-null   object 
 11  he-lazy-image src    7649 non-null   object 
 12  he-lazy-image src 2  4067 non-null   object 
 13  list-view-header     8129 non-null   object 
 14  branded__text        134 non-null    object 
 15  branded__text 2      134 non-null    o

In [144]:
df.columns

Index(['img-link href', 'photo-count', 'list-view-price', 'list-view-date',
       'left', 'celly', 'celly 2', 'celly 3', 'celly 4', 'list-view-location',
       'img-wrp href', 'he-lazy-image src', 'he-lazy-image src 2',
       'list-view-header', 'branded__text', 'branded__text 2',
       'img-wrp href 2', 'he-lazy-image src 3'],
      dtype='object')

In [145]:
cols=[ 'photo-count',  'list-view-date','left','list-view-location','img-wrp href', 'he-lazy-image src', 'he-lazy-image src 2','list-view-header', 'branded__text', 'branded__text 2','img-wrp href 2', 'he-lazy-image src 3']
drop_columns(df,cols)

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   img-link href    8136 non-null   object
 1   list-view-price  8136 non-null   object
 2   celly            8136 non-null   object
 3   celly 2          8136 non-null   object
 4   celly 3          8136 non-null   object
 5   celly 4          6858 non-null   object
dtypes: object(6)
memory usage: 381.5+ KB


In [147]:
df['location'] = df['img-link href'].apply(lambda x: x.split('/')[3])
df['city'] = df['location'].str.split('-').str[0]
df['district'] = df['location'].str.split('-').str[1]
df['neighborhood'] = df['location'].str.split('-').str[2:-1]
df['neighborhood'] = df['neighborhood'].apply(lambda x : '_'.join(x))


In [148]:
df.columns

Index(['img-link href', 'list-view-price', 'celly', 'celly 2', 'celly 3',
       'celly 4', 'location', 'city', 'district', 'neighborhood'],
      dtype='object')

In [149]:
drop_columns(df,['img-link href','location'])

In [150]:
df.columns

Index(['list-view-price', 'celly', 'celly 2', 'celly 3', 'celly 4', 'city',
       'district', 'neighborhood'],
      dtype='object')

In [151]:
df['celly'].unique()

array(['1 +\n                        1', '3 +\n                        1',
       '2 +\n                        1', '4 +\n                        1',
       '4 +\n                        2', '5 +\n                        1',
       '6 +\n                        1', '7 +\n                        1',
       '21 +\n                        1',
       '6 +\n                        2', '5 +\n                        2',
       'Stüdyo', '7 +\n                        2',
       '3 +\n                        2', '2 +\n                        0',
       '6 +\n                        0', '9 +\n                        4',
       '9 +\n                        1', '3 +\n                        0',
       '1 +\n                        15',
       '2 +\n                        2', '8 +\n                        1',
       '41 +\n                        4',
       '4 +\n                        0',
       '1 +\n                        25',
       '4 +\n                        4', '3 +\n                  

In [152]:
df['celly'] = df['celly'].apply(lambda x: x.replace('Stüdyo','1 + 0'))
df['celly'] = df['celly'].apply(lambda x: x.replace('\n',''))
df['room'] = df['celly'].apply(lambda x: x.split('+')[0]).astype(int)
df['livingRoom'] = df['celly'].apply(lambda x: x.split('+')[1]).astype(int)

In [153]:
drop_columns(df,['celly'])

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   celly 2          8136 non-null   object
 2   celly 3          8136 non-null   object
 3   celly 4          6858 non-null   object
 4   city             8136 non-null   object
 5   district         8136 non-null   object
 6   neighborhood     8136 non-null   object
 7   room             8136 non-null   int32 
 8   livingRoom       8136 non-null   int32 
dtypes: int32(2), object(7)
memory usage: 508.6+ KB


In [155]:
df['celly 2'].unique()

array(['55 m²', '150 m²', '60 m²', '160 m²', '135 m²', '67 m²', '140 m²',
       '170 m²', '130 m²', '230 m²', '220 m²', '210 m²', '89 m²',
       '120 m²', '200 m²', '355 m²', '75 m²', '110 m²', '100 m²', '65 m²',
       '145 m²', '115 m²', '1.000 m²', '250 m²', '105 m²', '50 m²',
       '87 m²', '90 m²', '85 m²', '155 m²', '275 m²', '240 m²', '95 m²',
       '174 m²', '80 m²', '125 m²', '180 m²', '165 m²', '350 m²', '97 m²',
       '45 m²', '300 m²', '84 m²', '42 m²', '98 m²', '86 m²', '500 m²',
       '70 m²', '51 m²', '73 m²', '132 m²', '325 m²', '141 m²', '450 m²',
       '600 m²', '47 m²', '72 m²', '71 m²', '3.000 m²', '175 m²',
       '320 m²', '280 m²', '156 m²', '190 m²', '78 m²', '162 m²',
       '185 m²', '18 m²', '330 m²', '151 m²', '56 m²', '136 m²', '131 m²',
       '48 m²', '580 m²', '119 m²', '147 m²', '77 m²', '245 m²', '35 m²',
       '375 m²', '146 m²', '161 m²', '163 m²', '149 m²', '206 m²',
       '138 m²', '93 m²', '63 m²', '41 m²', '183 m²', '96 m²', '108 m²',
  

In [156]:
df['celly 2'] = df['celly 2'].apply(lambda x: x.replace('.',''))
df['area'] = df['celly 2'].apply(lambda x: x.split(' ')[0]).astype(int)


In [157]:
df['area'].unique()

array([  55,  150,   60,  160,  135,   67,  140,  170,  130,  230,  220,
        210,   89,  120,  200,  355,   75,  110,  100,   65,  145,  115,
       1000,  250,  105,   50,   87,   90,   85,  155,  275,  240,   95,
        174,   80,  125,  180,  165,  350,   97,   45,  300,   84,   42,
         98,   86,  500,   70,   51,   73,  132,  325,  141,  450,  600,
         47,   72,   71, 3000,  175,  320,  280,  156,  190,   78,  162,
        185,   18,  330,  151,   56,  136,  131,   48,  580,  119,  147,
         77,  245,   35,  375,  146,  161,  163,  149,  206,  138,   93,
         63,   41,  183,   96,  108,   76,  475,  359,  124,   91,  194,
         43, 4500,   68,  205,   20,  103,   53,  270,   58,  302,  505,
        800,  168,  154,  368,  178,   40,  750,   92,  181,  400,   30,
        260,  460,  390,   64,  360,  340,  550,   38,  121, 4000,  295,
        112,  137,   22,  128, 3200,  440,  122,  370,  380,  204,  148,
        142,  520,  166,  870,  143,   57,  286,   

In [158]:
df['celly 3'].unique()

array(['25\n                      Yaşında',
       '35\n                      Yaşında',
       '2\n                      Yaşında',
       '27\n                      Yaşında',
       '15\n                      Yaşında',
       '10\n                      Yaşında',
       '20\n                      Yaşında',
       '30\n                      Yaşında',
       '16\n                      Yaşında',
       '11\n                      Yaşında',
       '31\n                      Yaşında', 'Sıfır Bina',
       '5\n                      Yaşında',
       '26\n                      Yaşında',
       '12\n                      Yaşında',
       '4\n                      Yaşında',
       '6\n                      Yaşında',
       '22\n                      Yaşında',
       '23\n                      Yaşında',
       '29\n                      Yaşında',
       '3\n                      Yaşında',
       '8\n                      Yaşında',
       '33\n                      Yaşında',
       '50\n            

In [159]:
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace('Sıfır Bina', '0'))
df['celly 3'] = df['celly 3'].apply(lambda x: x.replace('\n', ' '))
df['age'] = df['celly 3'].apply(lambda x: x.split(' ')[0]).astype(int)

In [160]:
df['age'].unique()

array([ 25,  35,   2,  27,  15,  10,  20,  30,  16,  11,  31,   0,   5,
        26,  12,   4,   6,  22,  23,  29,   3,   8,  33,  50,   7,  18,
        32,  28,  14,  40,   9,  21,  45,  38,  19,  24,  17,   1,  36,
        34,  13,  42,  44,  43,  37,  55,  47,  39,  49,  52, 300, 199,
        48,  60,  61, 600, 100])

In [161]:
drop_columns(df,['celly 3'])

In [162]:
df['celly 4'].unique()

array(['Yüksek Giriş', '3. Kat', 'Ara Kat', '4. Kat', '2. Kat', 'Zemin',
       nan, 'Tripleks', 'Villa Katı', 'Bahçe Katı', '1. Kat', '8. Kat',
       '6. Kat', 'Giriş Katı', '5. Kat', '7. Kat', '21 ve üzeri',
       'En Üst Kat', 'Teras Katı', '13. Kat', 'Kot 1', '9. Kat',
       'Çatı Katı', '10. Kat', '12. Kat', 'Kot 2', '15. Kat',
       'Bodrum ve Zemin', '11. Kat', 'Kot 3', '18. Kat', '20. Kat',
       'Yarı Bodrum', '14. Kat', '16. Kat', '17. Kat', 'Asma Kat',
       'Bodrum', '19. Kat'], dtype=object)

In [166]:
replaceDict={
    'Kot 2':'-2. Kat',
    'Kot 1': '-1. Kat',
    'Kot 3':'-3. Kat',
    'Yüksek Giriş': '1. Kat',
    'Ara Kat': '3.Kat',
    'Zemin' : '0. Kat',
    'En Üst Kat' : '5. Kat',
    'Villa Katı': '0. Kat',
    'Bahçe Katı': '0. Kat',
    'Giriş Katı': '0. Kat',
    'Teras Katı': '5. Kat',
    '21 ve üzeri': '21. Kat',
    'Çatı Katı': '5. Kat',
    'Bodrum ve Zemin': '-1. Kat',
    'Yarı Bodrum': '-1. Kat',
    'Asma Kat': '1. Kat',
    'Bodrum': '-1. Kat',
    'Tripleks':'0. Kat',
}
df['celly 4'] = df['celly 4'].replace(replaceDict.keys(),replaceDict.values()).astype(str)
df['celly 4'].dropna(inplace=True)
df['floor']=df['celly 4'].apply(lambda x: x.split('.')[0]).astype(int)

In [167]:
df['floor'].unique()

array([ 1,  3,  4,  2,  0,  8,  6,  5,  7, 21, 13, -1,  9, 10, 12, -2, 15,
       11, -3, 18, 20, 14, 16, 17, 19])

In [ ]:
drop_columns(df,['celly 4'])

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   list-view-price  8136 non-null   object
 1   city             8136 non-null   object
 2   district         8136 non-null   object
 3   neighborhood     8136 non-null   object
 4   room             8136 non-null   int32 
 5   livingRoom       8136 non-null   int32 
 6   area             8136 non-null   int32 
 7   age              8136 non-null   int32 
 8   floor            8136 non-null   int32 
dtypes: int32(5), object(4)
memory usage: 413.3+ KB


In [173]:
df['list-view-price'].unique()

array(['12.000', '16.000', '200', '18.000', '45.000', '35.000', '25.000',
       '22.000', '15.000', '24.000', '240.000', '1.200.000', '30.000',
       '20.000', '180.000', '60.000', '10.500', '10.000', '55.000',
       '13.000', '12.500', '21.000', '250.000', '190.000', '42.500',
       '17.000', '11.000', '450.000', '27.500', '80.000', '23.000',
       '550.000', '19.750', '75.000', '50.000', '34.000', '19.500',
       '28.500', '24.500', '325.000', '28.000', '29.000', '750.000',
       '600.000', '16.750', '500.000', '14.000', '220.000', '19.000',
       '21.500', '350.000', '9.000', '14.500', '25.500', '18.500',
       '300.000', '480.000', '150.000', '5.000', '16.500', '525.000',
       '370.000', '13.750', '17.500', '27.000', '11.500', '200.000',
       '90.000', '64.000', '15.750', '118.000', '1.000.000', '400.000',
       '70.000', '13.500', '210.000', '38.000', '1.800.000', '31.500',
       '57.500', '49.900', '2.000', '4.875.000', '8.500', '700.000',
       '15.250', '7.000',

In [174]:
df['list-view-price'] = df['list-view-price'].astype(str).apply(lambda x : x.replace('.',''))
df['price'] = df['list-view-price'].astype(int)

In [175]:
df['price'].unique()

array([    12000,     16000,       200,     18000,     45000,     35000,
           25000,     22000,     15000,     24000,    240000,   1200000,
           30000,     20000,    180000,     60000,     10500,     10000,
           55000,     13000,     12500,     21000,    250000,    190000,
           42500,     17000,     11000,    450000,     27500,     80000,
           23000,    550000,     19750,     75000,     50000,     34000,
           19500,     28500,     24500,    325000,     28000,     29000,
          750000,    600000,     16750,    500000,     14000,    220000,
           19000,     21500,    350000,      9000,     14500,     25500,
           18500,    300000,    480000,    150000,      5000,     16500,
          525000,    370000,     13750,     17500,     27000,     11500,
          200000,     90000,     64000,     15750,    118000,   1000000,
          400000,     70000,     13500,    210000,     38000,   1800000,
           31500,     57500,     49900,      2000, 

In [176]:
drop_columns(df,['list-view-price'])

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   city          8136 non-null   object
 1   district      8136 non-null   object
 2   neighborhood  8136 non-null   object
 3   room          8136 non-null   int32 
 4   livingRoom    8136 non-null   int32 
 5   area          8136 non-null   int32 
 6   age           8136 non-null   int32 
 7   floor         8136 non-null   int32 
 8   price         8136 non-null   int32 
dtypes: int32(6), object(3)
memory usage: 381.5+ KB


In [178]:
df.to_csv('data.csv',index=False)